# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
city1=CityInformation.create(image:'https://www.arabnews.com/sites/default/files/styles/n_670_395/public/2020/02/12/1968706-486009869.jpg?itok=xUNp4jvC',city_name:'Alula',city_about:'AlUla is a governorate of the Medina Region and a city in north-western Saudi Arabia. Historically located on the incense route, the city lies within the Governorate of Ula one of seven in the Medina Region.',living_cost:1500,best_time_visit:'winter')
city2=CityInformation.create(image:'https://i1.wp.com/neomsaudicity.net/wp-content/uploads/2018/08/Di9FnidXcAEt6Zd.jpg',city_name:'Neom',city_about:'is a planned cross-border city in the Tabuk Province of northwestern Saudi Arabia. It is planned to incorporate smart city technologies and also function as a tourist destination. The site is near the Red Sea',living_cost:1000,best_time_visit:'summer')
city3=CityInformation.create(image:'https://371081-1160199-raikfcquaxqncofqfm.stackpathdns.com/wp-content/uploads/2018/08/%D8%A7%D9%84%D9%85%D8%AF%D9%8A%D9%86%D8%A9-%D8%A7%D9%84%D9%85%D9%86%D9%88%D8%B1%D8%A9-1024x768.jpg',city_name:'Al-madina',city_about:'the city heart is al-Masjid an-Nabawi (The Prophet Mosque), which is the burial place of the Islamic prophet, Muhammad. Medina is one of the three holiest cities in Islam, the other two being Mecca and Jerusalem.',living_cost:200,best_time_visit:'anytime')
city4=CityInformation.create(image:'https://rahhal.wego.com/wp-content/uploads/2020/05/shutterstock_298483886_kpabzm.jpg',city_name:'Makkah',city_about:'Mecca was the site of Muhammad first revelation of the Quran, and a pilgrimage to it, known as the Hajj, is obligatory for all able Muslims. Mecca is home to the Kaaba, one of Islam holiest sites and the direction of Muslim prayer, and thus Mecca is regarded as the holiest city in Islam',living_cost:200,best_time_visit:'anytime')
city5=CityInformation.create(image:'https://www.arabnews.com/sites/default/files/styles/n_670_395/public/02/01/2017//1483290649581109600.jpg?itok=wMIeKfCK',city_name:'Abha',city_about:'is the capital of Asir Region in Saudi Arabia. It is situated 2,270 metres (7,450 feet) above sea level in the fertile Asir Mountains of south-western Saudi Arabia, near Asir National Park. Abha mild climate makes it a popular tourist destination for Saudis.',living_cost:300,best_time_visit:'summer')
city6=CityInformation.create(image:'https://www.arabnews.com/sites/default/files/styles/n_670_395/public/2020/02/05/1957556-930495522.jpg?itok=LpMevhgt',city_name:'Riyadh',city_about:'is the capital of Saudi Arabia and the largest city on the Arabian Peninsula. Riyadh is the political and administrative centre of Saudi Arabia and is the headquarters of the country central government bodies, such as the Saudi Royal Court and the Council of Ministers of Saudi Arabia.',living_cost:400,best_time_visit:'winter')
city7=CityInformation.create(image:'https://www.arabnews.com/sites/default/files/styles/n_670_395/public/2019/11/01/1824716-328889300.jpg?itok=uMs-cm1j',city_name:'Taif',city_about:'Taif is a city in Mecca Province of Saudi Arabia, is the 5th largest city in Saudi Arabia and the unofficial summer capital. The city is the center of an agricultural area known for its grapes, pomegranate, figs, roses and honey.
Taif is well known as the "City of Roses" and the best summer destination in Saudi Arabia as it enjoys a nice weather during summer',living_cost:300,best_time_visit:'summer')
city8=CityInformation.create(image:'https://www.arabnews.com/sites/default/files/styles/n_670_395/public/main-image/2018/10/19/1343441-263337249.jpg?itok=WqHeg44T
',city_name:'Jeddah',city_about:'is a city in the Hejaz region of Saudi Arabia and the country commercial center. Jeddah is the second-largest in Saudi Arabia. Jeddah was independently ranked fourth in the Africa – Mid-East region in terms of innovation in 2009 in the Innovation Cities Index',living_cost:400,best_time_visit:'winter')

Place.create(image:'https://lh5.googleusercontent.com/p/AF1QipOatzX5APxyCQ06Y9NDEzsYuMFJDI5e8FlyIPOH=w592-h404-n-k-no',place:'First Alaula museum',description:'Al-Ula Museum is a museum of civilization and history of the Al-Ula region. The museum is located in Al-Ula Governorate, Al-Madinah Al-Munawwarah Region in Saudi Arabia. It is affiliated with the General Authority for Tourism and National Heritage. The museum was built in (1405 AH) corresponding to 1985 AD on a land area of 10380 square meters, and it was opened to receive visitors in (1407 AH) corresponding to 1987 AD.',city_information:city1)
Place.create(image:'https://t3.gstatic.com/images?q=tbn:ANd9GcTKODHUV0CMBBRhKPxuaiiU4cTDHZ8uETYrAvTvRb-2TUSRCHh-nDxaBYtWII-VNhT8sMHbRQjejDi9NA',place:'The Elephant Mountain',description:'The Elephant Mountain is a huge rock 50 meters above the ground and is distinguished by its unique shape that resembles the elephant and from it acquired this name and surrounded by the rock a group of light-colored mountains and is located in a wide area covered with golden sands 7 km to the east of the Al-Ula governorate of the region Madina El Monawara.',city_information:city1)
Place.create(image:'https://d302e0npexowb4.cloudfront.net/wp-content/uploads/2019/10/29160947/neom.jpeg',place: 'the land of the future',description:'Coming Soon...',city_information:city2)
Place.create(image:'https://lh5.googleusercontent.com/proxy/-X48RIkt5PLx3P-XaMurdFi_Hf56ayju8VAyYFJCX9_cWBZ8t2VcWwNWFAxAa9W-S8pUSQdr9AxVYBuLlnS2MrN6-nEzLGgueo3eNOk-i8zhFz_tyPHgcT_keuzOaYydCxF9q2BGQ2OEd9Bwk0Msuz1BHnPv9u_YZIGp-d1J_dEN=w592-h404-n-k-no',place:'Prophet Mosque',description:'Prophet’s Mosque is one of the largest mosques in the world and the second holiest site in Islam. It is the mosque that the Prophet Muhammad built in Medina after his migration in AH 1, 622 AH, next to his house after the construction of the Quba Mosque.',city_information:city3)
Place.create(image:'https://lh3.googleusercontent.com/proxy/ByTFUXwEJIkViQkaKEFyRLICH-tQqkSAw4awo8tVmqFGotmy-_j5iP7eaypBEihr46QrJkjbrMr5zyvETTsQ2_3-Xy3pIHXl1kunv_KNq4KT4X6d51aUtMslTLRZlH0U6FVqBDubwyUzWseQSAj2RicwVlPDknI4AAeSgvNy6Bvq=w592-h404-n-k-no',place:'Mount Uhud',description:'Mount Uhud is a mountain that overlooks the Medina from the north, and was three and a half miles away from it before it was built by Imran. And 4 km from the Prophet’s Mosque. The mountain runs as a chain from east to west and tilts to the north. Mount Uhud witnessed several events after the rise of Islam and its religious status',city_information:city3)
Place.create(image:'https://i0.wp.com/www.saudiarabiatourismguide.com/wp-content/uploads/2016/10/Masjid-Al-Haram-photo-Menj-9.jpg?fit=2000%2C1312',place:'Makkah - The Grand Mosque',description:'The Grand Mosque is the greatest mosque in Islam and is located in the heart of the city of Mecca in the west of the Kingdom of Saudi Arabia, surrounded by the Kaaba, which is the first house placed for people on the face of the earth to worship God according to the Islamic faith',city_information:city4)
Place.create(image:'https://usercontent2.hubstatic.com/13869633_f520.jpg',place:'Jabal Al-Sooda or Black Mountain',description:'Abha is also home to the highest peak in Saudi Arabia, the Jabal Al-Sooda or Black Mountain, which stood at 2 miles (3.3km) high. It is the highlight of any trip to this area for a breathtaking vista of the city and the surrounding area.',city_information:city5)
Place.create(image:'https://usercontent1.hubstatic.com/8347538.jpg',place:'Stone houses of Rijal Almaa tribes, not far from Abha',description:'If you drive to the outskirts of Abha, you will see more of these mud and stone houses and in the old villages, these houses are at least 300 years old. If you are with a tour guide, you will learn the construction techniques of these houses, which is something worth knowing.',city_information:city5)
Place.create(image:'https://t2.gstatic.com/images?q=tbn:ANd9GcTAVJuW7GaPRlHz1doSSGKxOUL9KlnzfwW58bgyaCdEPryLlHB_UWGAuG3hLrUY5aMfQKbnPNXGAsZEWA',place:'Al faisaliya tower',description:'Al-Faisaliah Tower is one of the most prominent buildings in Riyadh. It is built on an area of 55 thousand square meters, in the center of Riyadh, in the Olaya district',city_information:city6)
Place.create(image:'https://lh5.googleusercontent.com/p/AF1QipMBHFROi3eOXqVq2auWW8H8kIb81jqE1KFpjBe6=w592-h404-n-k-no',place:'Al Ruddaf Park',description:'Very good park in Taif, lot of food and fun options. Very good grass, flowers and landscaping. Must visit place if you live in near vicinity',city_information:city7)
Place.create(image:'https://lh4.googleusercontent.com/proxy/dX72t2hTxj5vgvm_iERi9xKtGjErwfipf74b8ZiQraDVTiY6ERabhrsyAsXffMRWRVxitpg2sgy429bFRGG-OWnio8-j_HEKGCfYAt_e30RU1aJQ9i8noUeVJkVUVpVVxXZiJ3n7V5G5tsRZHXGig7tTskg20JQZoq01ryKuXYNW=w592-h404-n-k-no',place:'King Fahad fountain',description:'The King Fahd or Jeddah Fountain is the highest fountain of its kind in the world according to the Guinness Book of Records. It is located in front of the beaches of Jeddah on the western shore of Saudi Arabia on the Red Sea and is considered one of the landmarks of the city of Jeddah',city_information:city8)
Place.create(image:'https://lh5.googleusercontent.com/p/AF1QipPWi5M4uHTlmn5w-ecTzXxzq5_YhaAKAok4G2Ek=w592-h404-n-k-no',place:'Historic Jeddah',description:'Historic Jeddah, known locally as the city of Jeddah, is located in the center of the city of Jeddah, and dates - according to some sources - to pre-Islamic times',city_information:city8)

Package.create(destination:'Jeddah-Neom',flight:'king abdulaizi airport',hotel:3,plan:'Day 1: Diving,Day 2:Fishing',price:3000)
Package.create(destination:'Riyadh',flight:'king khalid airport',hotel:2,plan:'Day 1: Shopping,Day 2:Kingdom Centre',price:1000)
Package.create(destination:'Abha',flight:'Abha International Airport',hotel:3,plan:'Day 1: Go to park,Day 2:Art Street',price:1500)
package11=Package.create(destination:'Makkah',flight:'king abdulaizi airport',hotel:3,plan:'Day 1: Visit the Kaaba,Day 2:Mount Arafat',price:4000)
User.create(name:'maram',email:'m@g.com',password:'123321',password_confirmation:'123321')

# Order.create(user_id:5,package_id:3,member:23)
